// <auto-generated />
using Imenik.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace zadatakZaProgramere.Migrations
{
    [DbContext(typeof(ImenikContext))]
    partial class ImenikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Imenik.Models.Kontakti", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("grad");

                    b.Property<string>("ime");

                    b.Property<string>("opis");

                    b.Property<string>("prezime");

                    b.Property<string>("slika");

                    b.HasKey("id");

                    b.ToTable("kontakti");
                });

            modelBuilder.Entity("Imenik.Models.Telefon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Kontaktiid");

                    b.Property<string>("broj");

                    b.Property<string>("opis");

                    b.Property<string>("tip");

                    b.HasKey("id");

                    b.HasIndex("Kontaktiid");

                    b.ToTable("telefon");
                });

            modelBuilder.Entity("Imenik.Models.Telefon", b =>
                {
                    b.HasOne("Imenik.Models.Kontakti")
                        .WithMany("telefon")
                        .HasForeignKey("Kontaktiid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
